name: build
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - run: docker build -t raagpc/raag_gif_converter:0.9.1 . 
      - run: docker-compose -f docker-compose.yml up -d --force-recreate

